### ISSUE TITLE
Looking which sources we can use to get the information

### ISSUE THREAD

**Issue by liliana3186** [sbv-world-health-org-metrics/sbv-world-health-org-metrics#10]
Looking to fill this table with possible sources of data 
Project: [World Health Org Metrics](https://github.com/users/liliana3186/projects/1)

|                  |         Repositories         |       Members      |              Projects             |    Labels (bugs)   |       Commits      | Discussions |   Users Snapshot   | [Contribution attribution](https://chaoss.community/kb/metric-contribution-attribution/) | [Organizational Diversity](https://chaoss.community/kb/metric-organizational-diversity/) | [Elephant Factor](https://chaoss.community/kb/metric-elephant-factor/) | [Project Awareness](https://chaoss.community/kb/metrics-model-project-awareness/) | [Project Velocity](https://chaoss.community/kb/metric-project-velocity/) | [License Coverage](https://chaoss.community/kb/metric-license-coverage/) |
|:----------------:|:----------------------------:|:------------------:|:---------------------------------:|:------------------:|:------------------:|:-------------:|:------------------:|:----------------------------------------------------------------------------------------:|:----------------------------------------------------------------------------------------:|:----------------------------------------------------------------------:|:---------------------------------------------------------------------------------:|:------------------------------------------------------------------------:|:------------------------------------------------------------------------:|
|     REST API     | :heavy_check_mark:  (public) |         :x:        |                                   |                    |                    |             |                    |                                                                                          |                                                                                          |                                                                        |                                                                                   |                                                                          |                                                                          |
|      GRAPHQL     | :heavy_check_mark:  (public) |         :x:        |                                   |                    |                    |             |                    |                                                                                          |          :heavy_check_mark:  (Public)           |                                                                        |                                                                                   |                                                                          |                       :heavy_check_mark:  (public)                       |
| REST API (token) |      :heavy_check_mark:      |                    |                                   | :heavy_check_mark: |                    |             |                    |                                                                                          |                                                                                          |                                                                        |                                                                                   |                                                                          |                            :heavy_check_mark:                            |
|  GRAPHQL (token) |      :heavy_check_mark:      | :heavy_check_mark: | :heavy_check_mark: (classic + v2) | :heavy_check_mark: | :heavy_check_mark: | \:heavy_check_mark: |      ❓ Privacy     |                               :heavy_check_mark: :warning:                               |   \  :heavy_check_mark:    |                                                                        |                                                                                   |                                                                          |                            :heavy_check_mark:                            |
|    Stafftools    |      :heavy_check_mark:      | :heavy_check_mark: |         :heavy_check_mark:        |                    | :heavy_check_mark: |     :heavy_check_mark:        | :heavy_check_mark: |                                                                                          |                                                                                          |                                                                        |                                                                                   |                                                                          |                                                                          |
|   Datawarehouse  |      :heavy_check_mark:      |                    |                                   |                    |                    |             |                    |                                                                                          |                                                                                          |                                                                        |                                                                                   |                                                                          |                                                                          |
You can now import Markdown table code directly using File/Paste table data... dialog.

Comments:

**Users Snapshot:**
Considering the author of a Commit/PR/Comment - [Fields Available for User](https://docs.github.com/en/enterprise-cloud@latest/graphql/reference/objects#user)
 - [x] Country, 
 - [x] Region, 
 - [x] types of institutions, 
   - [x] company
   - [x] Sponsored
   - [x] Organization
   - [x] From Github
 - :x: status of implementation, 
 - :x: scope of implementation, 
 - :x: disease/use cases

:warning: There is something on this results that may not be complete or accurate

**Comment by liliana3186** [comment]
Comments
![Image](https://user-images.githubusercontent.com/12959012/228375038-523e32d0-bb0e-4079-aa8f-b7c866381096.png)

**Comment by darostegui** [comment]
I used [github-to-sqlite](https://github.com/dogsheep/github-to-sqlite) to get Repository information into SQLlite format using the REST API, It's not all the data we require but it covers 80% of the requirements and it can be used as the backbone for the project. 

We can, later on, use GraphQl to get the remaining 20% (user data, more repository information, etc) of the data.

The speed is good enough to grab all repositories in less than 30 minutes, so we will update the full information once every 1 or 2 hours.

CC:  @liliana3186 @hasan-dot

**Comment by liliana3186** [comment]
THis has been completed
