### ISSUE TITLE
Metric: Issues opened in periods of time

### ISSUE THREAD

**Issue by hasan-dot** [sbv-world-health-org-metrics/sbv-world-health-org-metrics#44]
This issue tracks the completeness of the metric.

Business Question: How many issues where open in a certain period of time?

How to calculate: Issue Count by Status File details of metrics [here](https://docs.google.com/spreadsheets/d/1wfG56fRevfbEIOgDoR3_uFyaq9cd30HxrwDcjbzi3uo/edit#gid=0)

### Tasks
- [ ] Create/update backend to fetch Issues by Status
- [ ] Visualize it in the frontend

**Comment by ipc103** [comment]
@Lehcar this might be a good one to dive into! I _think_ that, given the data we're already pulling to calculate issue resolution time, we can also calculate how many issues were open 30, 60, and 90 days ago. That'd let us do some charting/trends around whether issues are going up or down for a given repo. Let me know if that makes sense!

**Comment by Lehcar** [comment]
I'm a bit confused what [this line](https://github.com/sbv-world-health-org-metrics/sbv-world-health-org-metrics/blob/95a48d442f8e077dd91c31bd3977f4ccfc0ca991/ts-backend/src/fetchers/issues.ts#L110) `const issues = result.filter((issue) => !issue.pull_request);` does here. Is it saying that any issue without a PR is an open issue, or does graphQL return both pull_requests and issues, and we're just filtering out the PRs?

**Comment by Lehcar** [comment]
Also, here's my first pass/draft of how to do this: https://github.com/sbv-world-health-org-metrics/sbv-world-health-org-metrics/compare/main...issues-by-status, but I think I'd like to pair on this to make sure my approach is ok/to make sure I'm understanding this correctly 😅

**Comment by ajhenry** [comment]
We are going to be closing this issue as out of scope for now.

We need true historical data in order to correctly calculate these metrics.
