### ISSUE TITLE
Create a GitHub App to commit metrics

### ISSUE THREAD

**Issue by dmgardiner25** [sbv-world-health-org-metrics/sbv-world-health-org-metrics#53]
At the moment, we are using @hasan-dot's info [to commit metrics](https://github.com/sbv-world-health-org-metrics/sbv-world-health-org-metrics/blob/9c51e870ed72d1997d5b00028deac4eb06c14440/.github/workflows/graphql.yml#L62) that we fetch in our action. We could instead [create a GitHub App](https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app) so we don't have to use an individual user's info.

**Comment by liliana3186** [comment]
This will be great.

**Comment by ajhenry** [comment]
We could piggyback off of the actions[bot] if we want since that has permission to create commits and pull requests. Then we wouldn't need to maintain a bot

**Comment by ipc103** [comment]
Now that we're generating a data.json file as part of the build instead of opening a PR to the repo, I'm going to close this. We can re-open if this becomes needed in the future!
