### ISSUE TITLE
Feature: Retry data collection on error

### ISSUE THREAD

**Issue by ipc103** [sbv-world-health-org-metrics/sbv-world-health-org-metrics#66]
Right now, our main process fails if we record an error from a single fetcher/collector. We should really retry on some errors, and potentially preserve the data we've already collected.

Right now, we're running with a single collector, but in a multi-collector world we'd want all of these to succeed or fail independently.

**Comment by Lehcar** [comment]
I think we have this now since we're using the [plugin-retry.js](https://github.com/octokit/plugin-retry.js/) plugin! 

Should we close this?

**Comment by ipc103** [comment]
Yep, the TS conversion took care of this!
