### ISSUE TITLE
Metric: Issues Age

### ISSUE THREAD

**Issue by liliana3186** [sbv-world-health-org-metrics/sbv-world-health-org-metrics#72]
- When fetching total count of issues, also grab all the created_at dates of all of the open issues
- Calculate how many days each issue has been open
- Export the mean and median days issue_days_open per repository into the `data.json` file

**Comment by Lehcar** [comment]
👋 I'm going to try and attempt this. 

I will be OOO Dec 11, 2023 - Dec 15, 2023 so feel free to pick this up while I'm out :)

**Comment by Lehcar** [comment]
Yesterday, I tried creating a graphql query using the [explorer tool](https://docs.github.com/en/graphql/overview/explorer) and the [docs](https://docs.github.com/en/graphql/reference/objects#issue).

I ended up adding a new file with the following query (I'm new to graphql so please let me know if I can optimize this):
```
{
  organization(login: "WorldHealthOrganization") {
    repositories(first: 100, privacy: PUBLIC) {
 			edges {
        node {
          issues(last:100, states:OPEN) {
            edges {
              node {
                createdAt
              }
            }
          }
        }
      }
    }
  }
}
```
I created a branch ([calculate-issue-age](https://github.com/sbv-world-health-org-metrics/sbv-world-health-org-metrics/tree/calculate-issue-age)) with this query so far.
<br>
I'm not sure if we need to create a separate query/file to get this information. I originally tried modifying the existing `org-repos-info.graphql` query, but the explorer was returning errors (`"Field 'issues' has an argument conflict: {last:\"100\",states:\"OPEN\"} or {}?"`):

<details>
  <summary> modifying the `org-repos-info.graphql` query attempt </summary>

```
{
  organization(login: "WorldHealthOrganization") {
    repositories(first: 100, privacy: PUBLIC) {
      edges {
        node {
          issues(last:100, states:OPEN) {
            edges {
              node {
                createdAt
              }
            }
          }
          collaborators {
            totalCount
          }
          nameWithOwner
          projects {
            totalCount
          }
          projectsV2 {
            totalCount
          }
          discussions {
            totalCount
          }
          forks {
            totalCount
          }
          isPrivate
          issues {
            totalCount
          }
          licenseInfo {
            name
          }
          watchers {
            totalCount
          }
        }
      }
    }
  }
}
```
</details>

**Comment by Lehcar** [comment]
```
{
  organization(login: "WorldHealthOrganization") {
    repositories(first: 100, privacy: PUBLIC) {
      edges {
        node {
          openIssue: issues(last:100, states:OPEN) {
            edges {
              node {
                createdAt
              }
            }
          }
          collaborators {
            totalCount
          }
          nameWithOwner
          projects {
            totalCount
          }
          projectsV2 {
            totalCount
          }
          discussions {
            totalCount
          }
          forks {
            totalCount
          }
          isPrivate
          issues {
            totalCount
          }
          licenseInfo {
            name
          }
          watchers {
            totalCount
          }
        }
      }
    }
  }
}
```

**Comment by Lehcar** [comment]
Ok, I updated that query. I'm working on forming the query with `githubv4`, but I'm getting errors because my structs aren't correct (I think) 😅 

I have:
```
		OpenIssues struct {
			TotalCount githubv4.Int
			Nodes      []struct {
				Issue struct {
					CreatedAt githubv4.DateTime
				}
			}
		} `graphql:"openIssues: issues(states: OPEN)"`
```

For          
```
 openIssues: issues(states:OPEN) {
            edges {
              node {
                createdAt
              }
            }
          }
```

**Comment by ipc103** [comment]
The data was added to our pull in #93 🥳 Last step is to add it to the data table for display to the user.  @Lehcar I can put a PR up for that today unless you feel like jumping on it?

**Comment by Lehcar** [comment]
> The data was added to our pull in [#93](https://github.com/sbv-world-health-org-metrics/sbv-world-health-org-metrics/pull/93) 🥳 Last step is to add it to the data table for display to the user. [@Lehcar](https://github.com/Lehcar) I can put a PR up for that today unless you feel like jumping on it?
>
Thanks for doing this! Sorry, I just saw this--I've been catching up on emails 😅

**Comment by ipc103** [comment]
No worries - it was fun and didn't take too long to do 😄
