### ISSUE TITLE
Metric: Issue Resolution Time

### ISSUE THREAD

**Issue by liliana3186** [sbv-world-health-org-metrics/sbv-world-health-org-metrics#74]

**Comment by Lehcar** [comment]
I'm going to look into doing this. I'll follow what we did for calculating the average issue response time.

**Comment by Lehcar** [comment]
Oh I think this is actually done here: https://github.com/sbv-world-health-org-metrics/sbv-world-health-org-metrics/blob/main/ts-backend/src/fetchers/issues.ts#L253-L256.

I'm going to unassign myself, but I think we can close this.

**Comment by ipc103** [comment]
Yep, we can close this one! This was closed by #96
